apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-config
  namespace: {{ include "relay.namespace" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
