apiVersion: v1
kind: Secret
metadata:
  name: relay-secrets
  namespace: {{ include "relay.namespace" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
